/**
 * Decorative, theme-swapped blog cover. Light variant shown by default, dark via
 * the `dark:` variant — both generated by scripts/render-blog-covers.mjs into
 * public/team/blog/<slug>-{light,dark}.webp.
 */
export function BlogCover({
  slug,
  className,
}: {
  slug: string;
  className?: string;
}) {
  return (
    <>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={`/team/blog/${slug}-light.webp`}
        alt=""
        aria-hidden
        className={`${className ?? ""} dark:hidden`}
        draggable={false}
      />
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={`/team/blog/${slug}-dark.webp`}
        alt=""
        aria-hidden
        className={`${className ?? ""} hidden dark:block`}
        draggable={false}
      />
    </>
  );
}
